-- SunPanel Cloudflare D1 数据库迁移脚本
-- 版本: 1.2.0
-- 执行: wrangler d1 migrations apply sunpanel-db
-- 描述: 更新多语言数据，补充完整的页面文本

-- 更新中文语言数据
UPDATE global_settings SET page_texts = '{
  "home": {
    "welcome": "欢迎使用 SunPanel",
    "searchPlaceholder": "请输入搜索内容",
    "addFirstGroup": "开始添加您的第一个分组和网站吧",
    "goAdmin": "前往管理后台",
    "loginToConfigure": "登录后开始配置"
  },
  "nav": {
    "admin": "管理后台",
    "logout": "退出登录",
    "backToHome": "返回首页",
    "home": "首页",
    "darkMode": "切换到深色模式",
    "lightMode": "切换到浅色模式"
  },
  "admin": {
    "dashboard": "仪表盘",
    "profile": "个人信息",
    "personalization": "个性化设置",
    "groups": "分组管理",
    "gallery": "图库",
    "settings": "全局设置",
    "users": "账号管理",
    "api": "API",
    "openAPI": "Open API",
    "about": "关于",
    "migration": "迁移",
    "dataMigration": "数据迁移",
    "publicGallery": "公共图库",
    "exportImport": "导出/导入",
    "user": "用户",
    "management": "管理",
    "confirmClose": "确定关闭",
    "closeConfirm": "确定要关闭管理后台吗？所有未保存的更改将丢失。"
  },
  "login": {
    "username": "用户名",
    "password": "密码",
    "nickname": "昵称",
    "confirmPassword": "确认密码",
    "submit": "提交",
    "register": "注册",
    "loading": "加载中...",
    "haveAccount": "已有账号？去登录",
    "noAccount": "没有账号？去注册",
    "backToHome": "返回首页"
  },
  "profile": {
    "title": "个人信息",
    "username": "用户名",
    "nickname": "昵称",
    "email": "邮箱",
    "language": "语言",
    "save": "保存",
    "cancel": "取消",
    "password": "密码",
    "currentPassword": "当前密码",
    "newPassword": "新密码",
    "confirmNewPassword": "确认新密码",
    "changePassword": "修改密码",
    "uploading": "上传中...",
    "uploadSuccess": "上传成功",
    "uploadError": "上传失败",
    "saveSuccess": "保存成功"
  },
  "groups": {
    "title": "分组管理",
    "addGroup": "添加分组",
    "editGroup": "编辑分组",
    "deleteConfirm": "确定要删除这个分组吗？该分组下的所有网站也将被删除。",
    "name": "名称",
    "icon": "图标",
    "websites": "个网站",
    "noGroups": "暂无分组",
    "addFirstGroup": "点击上方按钮添加第一个分组",
    "websiteTitle": "网站管理",
    "addWebsite": "添加网站",
    "editWebsite": "编辑网站",
    "deleteWebsiteConfirm": "确定要删除这个网站吗？",
    "url": "网址",
    "description": "描述",
    "color": "卡片颜色",
    "group": "分组",
    "openInNewTab": "新标签页打开",
    "showAsWindow": "小窗口模式",
    "noWebsites": "暂无网站",
    "addFirstWebsite": "点击上方按钮添加第一个网站",
    "namePlaceholder": "请输入分组名称"
  },
  "dashboard": {
    "title": "仪表盘",
    "groupCount": "分组数量",
    "websiteCount": "网站数量",
    "imageCount": "图片数量",
    "userCount": "用户数量",
    "quickActions": "快捷操作",
    "recentWebsites": "最近添加的网站",
    "recentGroups": "最近添加的分组",
    "noWebsites": "暂无网站",
    "noGroups": "暂无分组",
    "addGroup": "添加分组",
    "addWebsite": "添加网站",
    "uploadImage": "上传图片",
    "changeTheme": "更换主题",
    "exportData": "导出数据",
    "viewApi": "查看API"
  },
  "globalSettings": {
    "title": "全局设置",
    "websiteTitle": "网站标题",
    "websiteDescription": "网站描述",
    "language": "语言",
    "footerText": "页脚文字",
    "save": "保存",
    "resetCache": "重置缓存",
    "cacheResetSuccess": "缓存已重置"
  },
  "common": {
    "cancel": "取消",
    "save": "保存",
    "delete": "删除",
    "edit": "编辑",
    "add": "添加",
    "loading": "加载中...",
    "error": "发生错误",
    "success": "操作成功",
    "confirm": "确认",
    "yes": "是",
    "no": "否",
    "search": "搜索",
    "submit": "提交",
    "close": "关闭",
    "refresh": "刷新",
    "retry": "重试",
    "saving": "保存中...",
    "processing": "处理中...",
    "generating": "生成中..."
  }
}' WHERE language = 'zh-CN';

-- 更新英文语言数据
UPDATE global_settings SET page_texts = '{
  "home": {
    "welcome": "Welcome to SunPanel",
    "searchPlaceholder": "Enter search content",
    "addFirstGroup": "Start adding your first group and websites",
    "goAdmin": "Go to admin panel",
    "loginToConfigure": "Login to configure"
  },
  "nav": {
    "admin": "Admin Panel",
    "logout": "Logout",
    "backToHome": "Back to Home",
    "home": "Home",
    "darkMode": "Switch to dark mode",
    "lightMode": "Switch to light mode"
  },
  "admin": {
    "dashboard": "Dashboard",
    "profile": "Profile",
    "personalization": "Personalization",
    "groups": "Groups",
    "gallery": "Gallery",
    "settings": "Settings",
    "users": "Users",
    "api": "API",
    "openAPI": "Open API",
    "about": "About",
    "migration": "Migration",
    "dataMigration": "Data Migration",
    "publicGallery": "Public Gallery",
    "exportImport": "Export/Import",
    "user": "User",
    "management": "Management",
    "confirmClose": "Confirm Close",
    "closeConfirm": "Are you sure you want to close the admin panel? All unsaved changes will be lost."
  },
  "login": {
    "username": "Username",
    "password": "Password",
    "nickname": "Nickname",
    "confirmPassword": "Confirm Password",
    "submit": "Submit",
    "register": "Register",
    "loading": "Loading...",
    "haveAccount": "Already have an account? Login",
    "noAccount": "Don''t have an account? Register",
    "backToHome": "Back to Home"
  },
  "profile": {
    "title": "Profile",
    "username": "Username",
    "nickname": "Nickname",
    "email": "Email",
    "language": "Language",
    "save": "Save",
    "cancel": "Cancel",
    "password": "Password",
    "currentPassword": "Current Password",
    "newPassword": "New Password",
    "confirmNewPassword": "Confirm New Password",
    "changePassword": "Change Password",
    "uploading": "Uploading...",
    "uploadSuccess": "Upload Success",
    "uploadError": "Upload Error",
    "saveSuccess": "Save Success"
  },
  "groups": {
    "title": "Group Management",
    "addGroup": "Add Group",
    "editGroup": "Edit Group",
    "deleteConfirm": "Are you sure you want to delete this group? All websites in this group will also be deleted.",
    "name": "Name",
    "icon": "Icon",
    "websites": "websites",
    "noGroups": "No Groups",
    "addFirstGroup": "Click the button above to add your first group",
    "websiteTitle": "Website Management",
    "addWebsite": "Add Website",
    "editWebsite": "Edit Website",
    "deleteWebsiteConfirm": "Are you sure you want to delete this website?",
    "url": "URL",
    "description": "Description",
    "color": "Card Color",
    "group": "Group",
    "openInNewTab": "Open in New Tab",
    "showAsWindow": "Window Mode",
    "noWebsites": "No Websites",
    "addFirstWebsite": "Click the button above to add your first website",
    "namePlaceholder": "Enter group name"
  },
  "dashboard": {
    "title": "Dashboard",
    "groupCount": "Group Count",
    "websiteCount": "Website Count",
    "imageCount": "Image Count",
    "userCount": "User Count",
    "quickActions": "Quick Actions",
    "recentWebsites": "Recently Added Websites",
    "recentGroups": "Recently Added Groups",
    "noWebsites": "No Websites",
    "noGroups": "No Groups",
    "addGroup": "Add Group",
    "addWebsite": "Add Website",
    "uploadImage": "Upload Image",
    "changeTheme": "Change Theme",
    "exportData": "Export Data",
    "viewApi": "View API"
  },
  "globalSettings": {
    "title": "Global Settings",
    "websiteTitle": "Website Title",
    "websiteDescription": "Website Description",
    "language": "Language",
    "footerText": "Footer Text",
    "save": "Save",
    "resetCache": "Reset Cache",
    "cacheResetSuccess": "Cache Reset Successfully"
  },
  "common": {
    "cancel": "Cancel",
    "save": "Save",
    "delete": "Delete",
    "edit": "Edit",
    "add": "Add",
    "loading": "Loading...",
    "error": "Error Occurred",
    "success": "Operation Successful",
    "confirm": "Confirm",
    "yes": "Yes",
    "no": "No",
    "search": "Search",
    "submit": "Submit",
    "close": "Close",
    "refresh": "Refresh",
    "retry": "Retry",
    "saving": "Saving...",
    "processing": "Processing...",
    "generating": "Generating..."
  }
}' WHERE language = 'en-US';

-- 更新日文语言数据
UPDATE global_settings SET page_texts = '{
  "home": {
    "welcome": "SunPanelへようこそ",
    "searchPlaceholder": "検索内容を入力",
    "addFirstGroup": "最初のグループとウェブサイトの追加を開始しましょう",
    "goAdmin": "管理パネルへ",
    "loginToConfigure": "ログインして設定"
  },
  "nav": {
    "admin": "管理パネル",
    "logout": "ログアウト",
    "backToHome": "ホームに戻る",
    "home": "ホーム",
    "darkMode": "ダークモードに切り替え",
    "lightMode": "ライトモードに切り替え"
  },
  "admin": {
    "dashboard": "ダッシュボード",
    "profile": "プロフィール",
    "personalization": "パーソナライズ",
    "groups": "グループ管理",
    "gallery": "ギャラリー",
    "settings": "設定",
    "users": "ユーザー管理",
    "api": "API",
    "openAPI": "Open API",
    "about": "アバウト",
    "migration": "マイグレーション",
    "dataMigration": "データ移行",
    "publicGallery": "パブリックギャラリー",
    "exportImport": "エクスポート/インポート",
    "user": "ユーザー",
    "management": "管理",
    "confirmClose": "閉じる",
    "closeConfirm": "管理パネルを閉じてもよろしいですか？保存されていない変更はすべて失われます。"
  },
  "login": {
    "username": "ユーザー名",
    "password": "パスワード",
    "nickname": "ニックネーム",
    "confirmPassword": "パスワード確認",
    "submit": "送信",
    "register": "登録",
    "loading": "読み込み中...",
    "haveAccount": "アカウントをお持ちですか？ログイン",
    "noAccount": "アカウントをお持ちでないですか？登録",
    "backToHome": "ホームに戻る"
  },
  "profile": {
    "title": "プロフィール",
    "username": "ユーザー名",
    "nickname": "ニックネーム",
    "email": "メール",
    "language": "言語",
    "save": "保存",
    "cancel": "キャンセル",
    "password": "パスワード",
    "currentPassword": "現在のパスワード",
    "newPassword": "新しいパスワード",
    "confirmNewPassword": "新しいパスワード確認",
    "changePassword": "パスワード変更",
    "uploading": "アップロード中...",
    "uploadSuccess": "アップロード成功",
    "uploadError": "アップロードエラー",
    "saveSuccess": "保存成功"
  },
  "groups": {
    "title": "グループ管理",
    "addGroup": "グループ追加",
    "editGroup": "グループ編集",
    "deleteConfirm": "このグループを削除してもよろしいですか？このグループのすべてのウェブサイトも削除されます。",
    "name": "名前",
    "icon": "アイコン",
    "websites": "ウェブサイト",
    "noGroups": "グループがありません",
    "addFirstGroup": "上のボタンをクリックして最初のグループを追加",
    "websiteTitle": "ウェブサイト管理",
    "addWebsite": "ウェブサイト追加",
    "editWebsite": "ウェブサイト編集",
    "deleteWebsiteConfirm": "このウェブサイトを削除してもよろしいですか？",
    "url": "URL",
    "description": "説明",
    "color": "カードの色",
    "group": "グループ",
    "openInNewTab": "新しいタブで開く",
    "showAsWindow": "ウィンドウモード",
    "noWebsites": "ウェブサイトがありません",
    "addFirstWebsite": "上のボタンをクリックして最初のウェブサイトを追加",
    "namePlaceholder": "グループ名を入力"
  },
  "dashboard": {
    "title": "ダッシュボード",
    "groupCount": "グループ数",
    "websiteCount": "ウェブサイト数",
    "imageCount": "画像数",
    "userCount": "ユーザー数",
    "quickActions": "クイックアクション",
    "recentWebsites": "最近追加されたウェブサイト",
    "recentGroups": "最近追加されたグループ",
    "noWebsites": "ウェブサイトがありません",
    "noGroups": "グループがありません",
    "addGroup": "グループ追加",
    "addWebsite": "ウェブサイト追加",
    "uploadImage": "画像アップロード",
    "changeTheme": "テーマ変更",
    "exportData": "データエクスポート",
    "viewApi": "APIを表示"
  },
  "globalSettings": {
    "title": "グローバル設定",
    "websiteTitle": "ウェブサイトタイトル",
    "websiteDescription": "ウェブサイト説明",
    "language": "言語",
    "footerText": "フッターテキスト",
    "save": "保存",
    "resetCache": "キャッシュをリセット",
    "cacheResetSuccess": "キャッシュがリセットされました"
  },
  "common": {
    "cancel": "キャンセル",
    "save": "保存",
    "delete": "削除",
    "edit": "編集",
    "add": "追加",
    "loading": "読み込み中...",
    "error": "エラーが発生しました",
    "success": "操作に成功しました",
    "confirm": "確認",
    "yes": "はい",
    "no": "いいえ",
    "search": "検索",
    "submit": "送信",
    "close": "閉じる",
    "refresh": "更新",
    "retry": "再試行",
    "saving": "保存中...",
    "processing": "処理中...",
    "generating": "生成中..."
  }
}' WHERE language = 'ja-JP';

-- 更新韩文语言数据
UPDATE global_settings SET page_texts = '{
  "home": {
    "welcome": "SunPanel에 오신 것을 환영합니다",
    "searchPlaceholder": "검색 내용을 입력하세요",
    "addFirstGroup": "첫 번째 그룹과 웹사이트를 추가하기 시작하세요",
    "goAdmin": "관리 패널로",
    "loginToConfigure": "로그인하여 구성"
  },
  "nav": {
    "admin": "관리 패널",
    "logout": "로그아웃",
    "backToHome": "홈으로 돌아가기",
    "home": "홈",
    "darkMode": "다크 모드로 전환",
    "lightMode": "라이트 모드로 전환"
  },
  "admin": {
    "dashboard": "대시보드",
    "profile": "프로필",
    "personalization": "개인화",
    "groups": "그룹 관리",
    "gallery": "갤러리",
    "settings": "설정",
    "users": "사용자 관리",
    "api": "API",
    "openAPI": "Open API",
    "about": "정보",
    "migration": "마이그레이션",
    "dataMigration": "데이터 마이그레이션",
    "publicGallery": "공개 갤러리",
    "exportImport": "내보내기/가져오기",
    "user": "사용자",
    "management": "관리",
    "confirmClose": "닫기 확인",
    "closeConfirm": "관리 패널을 닫으시겠습니까? 저장되지 않은 모든 변경 사항이 손실됩니다."
  },
  "login": {
    "username": "사용자 이름",
    "password": "비밀번호",
    "nickname": "별명",
    "confirmPassword": "비밀번호 확인",
    "submit": "제출",
    "register": "등록",
    "loading": "로딩 중...",
    "haveAccount": "계정이 있으신가요? 로그인",
    "noAccount": "계정이 없으신가요? 등록",
    "backToHome": "홈으로 돌아가기"
  },
  "profile": {
    "title": "프로필",
    "username": "사용자 이름",
    "nickname": "별명",
    "email": "이메일",
    "language": "언어",
    "save": "저장",
    "cancel": "취소",
    "password": "비밀번호",
    "currentPassword": "현재 비밀번호",
    "newPassword": "새 비밀번호",
    "confirmNewPassword": "새 비밀번호 확인",
    "changePassword": "비밀번호 변경",
    "uploading": "업로드 중...",
    "uploadSuccess": "업로드 성공",
    "uploadError": "업로드 오류",
    "saveSuccess": "저장 성공"
  },
  "groups": {
    "title": "그룹 관리",
    "addGroup": "그룹 추가",
    "editGroup": "그룹 편집",
    "deleteConfirm": "이 그룹을 삭제하시겠습니까? 이 그룹의 모든 웹사이트도 삭제됩니다.",
    "name": "이름",
    "icon": "아이콘",
    "websites": "웹사이트",
    "noGroups": "그룹이 없습니다",
    "addFirstGroup": "위 버튼을 클릭하여 첫 번째 그룹을 추가하세요",
    "websiteTitle": "웹사이트 관리",
    "addWebsite": "웹사이트 추가",
    "editWebsite": "웹사이트 편집",
    "deleteWebsiteConfirm": "이 웹사이트를 삭제하시겠습니까?",
    "url": "URL",
    "description": "설명",
    "color": "카드 색상",
    "group": "그룹",
    "openInNewTab": "새 탭에서 열기",
    "showAsWindow": "창 모드",
    "noWebsites": "웹사이트가 없습니다",
    "addFirstWebsite": "위 버튼을 클릭하여 첫 번째 웹사이트를 추가하세요",
    "namePlaceholder": "그룹 이름을 입력하세요"
  },
  "dashboard": {
    "title": "대시보드",
    "groupCount": "그룹 수",
    "websiteCount": "웹사이트 수",
    "imageCount": "이미지 수",
    "userCount": "사용자 수",
    "quickActions": "빠른 작업",
    "recentWebsites": "최근 추가된 웹사이트",
    "recentGroups": "최근 추가된 그룹",
    "noWebsites": "웹사이트가 없습니다",
    "noGroups": "그룹이 없습니다",
    "addGroup": "그룹 추가",
    "addWebsite": "웹사이트 추가",
    "uploadImage": "이미지 업로드",
    "changeTheme": "테마 변경",
    "exportData": "데이터 내보내기",
    "viewApi": "API 보기"
  },
  "globalSettings": {
    "title": "전역 설정",
    "websiteTitle": "웹사이트 제목",
    "websiteDescription": "웹사이트 설명",
    "language": "언어",
    "footerText": "푸터 텍스트",
    "save": "저장",
    "resetCache": "캐시 초기화",
    "cacheResetSuccess": "캐시가 초기화되었습니다"
  },
  "common": {
    "cancel": "취소",
    "save": "저장",
    "delete": "삭제",
    "edit": "편집",
    "add": "추가",
    "loading": "로딩 중...",
    "error": "오류가 발생했습니다",
    "success": "작업 성공",
    "confirm": "확인",
    "yes": "예",
    "no": "아니오",
    "search": "검색",
    "submit": "제출",
    "close": "닫기",
    "refresh": "새로 고침",
    "retry": "다시 시도",
    "saving": "저장 중...",
    "processing": "처리 중...",
    "generating": "생성 중..."
  }
}' WHERE language = 'ko-KR';

-- 更新时间戳
UPDATE global_settings SET updated_at = datetime('now');
