CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    language TEXT DEFAULT 'zh-CN',
    nickname TEXT,
    avatar TEXT,
    email TEXT,
    role TEXT DEFAULT 'user' CHECK(role IN ('admin', 'user')),
    theme TEXT DEFAULT 'light',
    wallpaper TEXT DEFAULT '#1e293b',
    wallpaper_type TEXT DEFAULT 'color',
    show_search_bar INTEGER DEFAULT 1,
    search_engine TEXT DEFAULT 'https://www.bing.com/search?q=',
    items_per_row INTEGER DEFAULT 6,
    mobile_items_per_row INTEGER DEFAULT 2,
    tablet_items_per_row INTEGER DEFAULT 3,
    desktop_items_per_row INTEGER DEFAULT 6,
    show_group_names INTEGER DEFAULT 1,
    custom_css TEXT,
    custom_js TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);